# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket = "terragruntbk"
        key   =  "./terraform.tfstate"
        region = "us-east-1"
        encrypt = true
        dynamodb_table = "Terraform"
        profile = "shilohIT"
    }
}
