name: 'Terragrunt CI Final'

on:
  push:
    branches:
    - main
  pull_request:
permissions:
  packages: write  # This is required for requesting JWT
  contents: read   #This is required for action/checkout
  id-token: write
  

jobs:
  Terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    env:  
      DEPLOYMENT_PATH: Environments/Shiloh
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Configure aws credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terragrunt v0.55.9
      run: |
        echo "aws-access-key-id"
        echo "aws-secret-access-key"
    # Initialize a new or existing Terragrunt working directory by creating initial files, loading any remote state, downloading modules, etc.

